# -*- coding: utf-8 -*-
"""EDA Sentiments Vs. Date.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1re-dh3zI9x5LOvF0fRjezKZMhOBSlVFf
"""

import matplotlib.pyplot as plt

def generate_sentiment_plots(sentiment_list, companies):
    for com in companies:
        inp=[]
        label=[]
        for el in sentiment_list:
            if el[1]==com:
                inp.append(el[2])
                label.append(el[0])
        plt.plot(inp,label)
        plt.xticks([])
        plt.xlabel("<===Date===>")
        plt.ylabel("<===Sentiment Score===>")
        plt.title(f"For company {com}")
        plt.show()
        print("\n\n")