# -*- coding: utf-8 -*-
"""PriceDiff Vs. Sentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1re-dh3zI9x5LOvF0fRjezKZMhOBSlVFf
"""

for com in companies:
  inp=[]
  label=[]
  for el in sentiment_list:
    if el[1]==com:
      sent_score=0
      if el[0]>=0:
        sent_score=1
      diff_stock=el[4]-el[5]
      inp.append([sent_score,el[2],diff_stock])

  cur_df = pd.DataFrame (inp, columns = ['sentiment','date','diff_stock'])
  # showing the relation between stock,Compound_sentiment_score and date.
  stockVsSentiment = px.line(cur_df,
          x  = "date",
          y = "diff_stock",

          title = f"Showing relation between difference of stock,Compound_sentiment_score and date for company {com}<br><br>Hover over the dots to see details👇<br>",

          # color based on sentiment
          color = "sentiment",
)
  stockVsSentiment.show()
  # plt.plot(cur_df["date"],cur_df["stock"])
  # plt.xticks([])
  # plt.xlabel("<===Sentiment Score===>")
  # plt.ylabel("<===Current Stock Price===>")
  # plt.title(f"For company {com}")
  # plt.show()
  print("\n\n")